vendor: Talos Systems
hi: hi
name: Talos
version: v0.14.0
website_url: www.siderolabs.com
repo_url: <Not Available>
product_logo_url: https://www.talos.dev/images/TalosSystems_Horizontal_Logo_FullColor_RGB-for-site.svg
type: installer
description: Talos is a modern Kubernetes-focused OS designed to be secure, immutable, and minimal.
